# Generated by Django 2.1.5 on 2019-02-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_servicepagekeypoint_linked_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="is_darktheme",
            field=models.BooleanField(default=True),
        ),
    ]
