# Generated by Django 2.1.5 on 2019-02-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_servicepage_is_darktheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="is_darktheme",
            field=models.BooleanField(default=False),
        ),
    ]
