# Generated by Django 2.1.5 on 2019-02-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_servicepageherolink"),
    ]

    operations = [
        migrations.RemoveField(model_name="servicepageherolink", name="page",),
        migrations.DeleteModel(name="ServicePageHeroLink",),
    ]
