# Generated by Django 2.1.5 on 2019-02-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_auto_20190207_0252"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubServicePage",
            fields=[
                (
                    "servicepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="services.ServicePage",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("services.servicepage",),
        ),
    ]
