# Generated by Django 2.1.5 on 2019-02-07 16:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("services", "0014_subservicepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePageProcess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("link_label", models.TextField(blank=True)),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            options={"ordering": ["sort_order"], "abstract": False,},
        ),
        migrations.AddField(
            model_name="servicepage",
            name="process_section_title",
            field=models.TextField(blank=True, default="Process"),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="use_process_block_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicepageprocess",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_processes",
                to="services.ServicePage",
            ),
        ),
    ]
