# Generated by Django 2.1.5 on 2019-02-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_auto_20190207_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepageprocess",
            name="link_label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicepageprocess",
            name="link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.Page",
            ),
        ),
    ]
