# Generated by Django 2.1.5 on 2019-02-07 17:40

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0017_auto_20190207_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepageprocess",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processes",
                to="services.ServicePage",
            ),
        ),
    ]
