# Generated by Django 2.1.5 on 2019-02-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0021_auto_20190211_0705"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="heading_for_processes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
