# Generated by Django 2.1.5 on 2019-03-19 19:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_auto_20190316_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='heading_for_key_points',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
