# Generated by Django 2.1.5 on 2019-03-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0028_services_orderable_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="subservicepage",
            name="show_automatic_blog_listing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subservicepage",
            name="show_automatic_case_studies_listing",
            field=models.BooleanField(default=False),
        ),
    ]
