# Generated by Django 2.2.13 on 2020-11-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0029_subservice_listingsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subservicepage", name="show_automatic_blog_listing",
        ),
        migrations.RemoveField(
            model_name="subservicepage", name="show_automatic_case_studies_listing",
        ),
    ]
