# Generated by Django 2.2.17 on 2021-07-07 11:59

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0030_subservicepage_remove_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="process_section_cta",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="An opportunity to use a more flexible call to action, if the main “Contact” fields aren’t suitable",
                verbose_name="Process section CTA",
            ),
        ),
        migrations.AddField(
            model_name="subservicepage",
            name="process_section_cta",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="An opportunity to use a more flexible call to action, if the main “Contact” fields aren’t suitable",
                verbose_name="Process section CTA",
            ),
        ),
    ]
