# Generated by Django 2.2.17 on 2021-11-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0031_service_process_section_cta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepageclientlogo",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.CustomImage"
            ),
        ),
        migrations.AlterField(
            model_name="servicepageusaclientlogo",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.CustomImage"
            ),
        ),
        migrations.AlterField(
            model_name="subservicepageclientlogo",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.CustomImage"
            ),
        ),
        migrations.AlterField(
            model_name="subservicepageusaclientlogo",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="images.CustomImage"
            ),
        ),
    ]
