# Generated by Django 3.2.16 on 2023-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_service_add_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='embed_url',
            field=models.URLField(blank=True, verbose_name='Embed URL'),
        ),
        migrations.AddField(
            model_name='subservicepage',
            name='embed_url',
            field=models.URLField(blank=True, verbose_name='Embed URL'),
        ),
    ]
