# Generated by Django 3.2.18 on 2023-06-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_call_to_action'),
        ('services', '0040_update_services_theme'),
    ]

    operations = [
    ]
