# Generated by Django 3.2.20 on 2023-11-02 11:15

from django.db import migrations


def delete_pages(apps, schema_editor):
    SubServicePage = apps.get_model("services", "SubServicePage")
    ServicePage = apps.get_model("services", "ServicePage")
    SubServicePage.objects.all().delete()
    ServicePage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0042_add_social_fields_to_all_page_types"),
    ]

    operations = [
        migrations.RunPython(delete_pages),
    ]
