# Generated by Django 3.2.20 on 2023-11-02 13:11

from django.db import migrations


def delete_pages(apps, schema_editor):
    SubServicePage = apps.get_model("services", "SubServicePage")
    ServicePage = apps.get_model("services", "ServicePage")
    SubServicePage.objects.all().delete()
    ServicePage.objects.all().delete()


def nooperation(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0008_add_verbose_name_plural"),
        ("wagtailcore", "0083_workflowcontenttype"),
        ("wagtailforms", "0005_alter_formsubmission_form_data"),
        ("services", "0042_add_social_fields_to_all_page_types"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="servicepageclientlogo",
            name="image",
        ),
        migrations.RemoveField(
            model_name="servicepageclientlogo",
            name="page",
        ),
        migrations.RemoveField(
            model_name="servicepagefeaturedblogpost",
            name="blog_post",
        ),
        migrations.RemoveField(
            model_name="servicepagefeaturedblogpost",
            name="page",
        ),
        migrations.RemoveField(
            model_name="servicepagefeaturedcasestudy",
            name="case_study",
        ),
        migrations.RemoveField(
            model_name="servicepagefeaturedcasestudy",
            name="page",
        ),
        migrations.RemoveField(
            model_name="servicepagekeypoint",
            name="linked_page",
        ),
        migrations.RemoveField(
            model_name="servicepagekeypoint",
            name="page",
        ),
        migrations.RemoveField(
            model_name="servicepageprocess",
            name="page",
        ),
        migrations.RemoveField(
            model_name="servicepageprocess",
            name="page_link",
        ),
        migrations.RemoveField(
            model_name="servicepagetestimonial",
            name="page",
        ),
        migrations.RemoveField(
            model_name="servicepageusaclientlogo",
            name="image",
        ),
        migrations.RemoveField(
            model_name="servicepageusaclientlogo",
            name="page",
        ),
        migrations.RemoveField(
            model_name="subservicepage",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="subservicepage",
            name="contact_reasons",
        ),
        migrations.RemoveField(
            model_name="subservicepage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="subservicepage",
            name="social_image",
        ),
        migrations.RemoveField(
            model_name="subservicepageclientlogo",
            name="image",
        ),
        migrations.RemoveField(
            model_name="subservicepageclientlogo",
            name="page",
        ),
        migrations.RemoveField(
            model_name="subservicepagefeaturedblogpost",
            name="blog_post",
        ),
        migrations.RemoveField(
            model_name="subservicepagefeaturedblogpost",
            name="page",
        ),
        migrations.RemoveField(
            model_name="subservicepagefeaturedcasestudy",
            name="case_study",
        ),
        migrations.RemoveField(
            model_name="subservicepagefeaturedcasestudy",
            name="page",
        ),
        migrations.RemoveField(
            model_name="subservicepagekeypoint",
            name="linked_page",
        ),
        migrations.RemoveField(
            model_name="subservicepagekeypoint",
            name="page",
        ),
        migrations.RemoveField(
            model_name="subservicepageprocess",
            name="page",
        ),
        migrations.RemoveField(
            model_name="subservicepageprocess",
            name="page_link",
        ),
        migrations.RemoveField(
            model_name="subservicepagetestimonial",
            name="page",
        ),
        migrations.RemoveField(
            model_name="subservicepageusaclientlogo",
            name="image",
        ),
        migrations.RemoveField(
            model_name="subservicepageusaclientlogo",
            name="page",
        ),
        migrations.DeleteModel(
            name="ServicePage",
        ),
        migrations.DeleteModel(
            name="ServicePageClientLogo",
        ),
        migrations.DeleteModel(
            name="ServicePageFeaturedBlogPost",
        ),
        migrations.DeleteModel(
            name="ServicePageFeaturedCaseStudy",
        ),
        migrations.DeleteModel(
            name="ServicePageKeyPoint",
        ),
        migrations.DeleteModel(
            name="ServicePageProcess",
        ),
        migrations.DeleteModel(
            name="ServicePageTestimonial",
        ),
        migrations.DeleteModel(
            name="ServicePageUSAClientLogo",
        ),
        migrations.DeleteModel(
            name="SubServicePage",
        ),
        migrations.DeleteModel(
            name="SubServicePageClientLogo",
        ),
        migrations.DeleteModel(
            name="SubServicePageFeaturedBlogPost",
        ),
        migrations.DeleteModel(
            name="SubServicePageFeaturedCaseStudy",
        ),
        migrations.DeleteModel(
            name="SubServicePageKeyPoint",
        ),
        migrations.DeleteModel(
            name="SubServicePageProcess",
        ),
        migrations.DeleteModel(
            name="SubServicePageTestimonial",
        ),
        migrations.DeleteModel(
            name="SubServicePageUSAClientLogo",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunPython(delete_pages, nooperation),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        ),
    ]
