# Generated by Django 4.2.8 on 2024-01-02 19:08

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselandingpage",
            name="child_page_listing_heading",
            field=models.CharField(
                blank=True,
                help_text="A heading shown above the child pages listed.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="courselandingpage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="courselandingpage",
            name="strapline",
            field=models.CharField(
                default="",
                help_text="Words in <span> tag will display in a contrasting colour.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courselandingpage",
            name="sub_title",
            field=models.CharField(
                blank=True,
                help_text="Displayed just below the strapline.",
                max_length=255,
            ),
        ),
    ]
