# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_rename_streamfield_to_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="colour",
            field=models.CharField(
                blank=True,
                choices=[("orange", "Orange"), ("blue", "Blue"), ("white", "White")],
                help_text="Listing card colour if left blank will display image",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Used for blog index and Planet Drupal listings"
            ),
        ),
    ]
