# Generated by Django 2.0.7 on 2018-08-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='08/05/18 - 12:29', help_text='Deployment Title')),
                ('deployment_created', models.DateTimeField(auto_now_add=True)),
                ('deployment_time', models.DateTimeField(blank=True, help_text='Trigger deployment at this time (Leave blank to deploy now)', null=True)),
                ('deployment_created_by', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='NetlifySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netlify_url', models.URLField(help_text='URL of Netlify Site')),
                ('netlify_build_trigger', models.URLField(help_text='Netlify unique build trigger URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
