# Generated by Django 2.0.7 on 2018-08-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netlify', '0004_auto_20180805_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='deployment_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='title',
            field=models.TextField(default='08/05/18 - 14:27', help_text='Deployment Title'),
        ),
    ]
