# Generated by Django 2.2.9 on 2020-02-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headlesspreview', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='PagePreview')
    ]
