# Generated by Django 2.1.5 on 2019-02-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_personpage_short_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="personpage",
            name="alt_short_intro",
            field=models.TextField(blank=True, null=True),
        ),
    ]
