# Generated by Django 2.1.5 on 2019-02-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0009_personpage_alt_short_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="default_contact",
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
    ]
