# Generated by Django 2.1.5 on 2019-03-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20190316_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactreasonslist',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
