# Generated by Django 2.1.5 on 2019-03-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20190316_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturepage',
            name='strapline_visible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
