# Generated by Django 2.1.5 on 2019-03-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0013_culturepage_strapline_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactreasonslist",
            name="is_default",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
