# Generated by Django 2.2.12 on 2021-01-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0017_update_streamblock_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="default_contact",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
