# Generated by Django 2.2.17 on 2021-04-12 09:42

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0021_valuespagevalue_value_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valuespagevalue",
            name="heading",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="valuespagevalue",
            name="text",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
