# Generated by Django 2.2.17 on 2021-03-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0022_auto_20210326_1202"),
        ("people", "0022_culturepage_featured_blogs"),
    ]

    operations = []
