# Generated by Django 2.2.17 on 2021-04-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_merge_20210330_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='culturepage',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='culturepage',
            name='strapline_visible',
        ),
    ]
