# Generated by Django 2.2.17 on 2021-04-13 11:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_merge_20210330_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturepage',
            name='instagram_posts',
            field=wagtail.core.fields.StreamField([('post', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('post_url', wagtail.core.blocks.URLBlock())]))], blank=True),
        ),
    ]
