# Generated by Django 2.2.17 on 2021-04-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_auto_20210412_1428'),
        ('people', '0023_merge_20210330_1437'),
    ]

    operations = [
    ]
