# Generated by Django 2.2.17 on 2021-06-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0026_culturepage_instagram_posts"),
        ("people", "0024_auto_20210412_1428"),
    ]

    operations = []
