# Generated by Django 2.2.17 on 2021-06-04 11:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0027_merge_20210603_1719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="culturepage",
            name="standout_items",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "item",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("subtitle", wagtail.core.blocks.CharBlock()),
                                ("title", wagtail.core.blocks.CharBlock()),
                                ("description", wagtail.core.blocks.TextBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "link",
                                    wagtail.core.blocks.StreamBlock(
                                        [
                                            (
                                                "internal",
                                                wagtail.core.blocks.PageChooserBlock(),
                                            ),
                                            (
                                                "external",
                                                wagtail.core.blocks.URLBlock(),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
