# Generated by Django 2.2.17 on 2021-06-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0028_auto_20210604_1234"),
        ("people", "0025_merge_20210415_1359"),
    ]

    operations = []
