# Generated by Django 2.2.17 on 2021-07-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_auto_20210728_1109'),
        ('people', '0029_merge_20210604_1304'),
    ]

    operations = [
    ]
