# Generated by Django 2.2.17 on 2021-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0029_auto_20210728_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="personpage",
            name="title_extra",
            field=models.CharField(
                blank=True,
                help_text="Text that displays straight after the team members name",
                max_length=255,
            ),
        ),
    ]
