# Generated by Django 2.2.17 on 2021-11-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0030_merge_20210728_1132"),
        ("people", "0030_add_extra_title_field_to_person"),
    ]

    operations = []
