# Generated by Django 3.2.12 on 2022-04-22 14:15

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0030_update_image_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="culturepage",
            name="featured_blog_posts",
            field=wagtail.fields.StreamField(
                [
                    (
                        "blog_post",
                        wagtail.blocks.PageChooserBlock(page_type=["blog.BlogPage"]),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Blog posts",
            ),
        ),
        migrations.AlterField(
            model_name="culturepage",
            name="instagram_posts",
            field=wagtail.fields.StreamField(
                [
                    (
                        "post",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "link",
                                    wagtail.blocks.URLBlock(
                                        help_text="Link to a specific post here or leave blank for it to link to https://www.instagram.com/torchboxltd/",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="culturepage",
            name="standout_items",
            field=wagtail.fields.StreamField(
                [
                    (
                        "item",
                        wagtail.blocks.StructBlock(
                            [
                                ("subtitle", wagtail.blocks.CharBlock()),
                                ("title", wagtail.blocks.CharBlock()),
                                ("description", wagtail.blocks.TextBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "link",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "internal",
                                                wagtail.blocks.PageChooserBlock(),
                                            ),
                                            ("external", wagtail.blocks.URLBlock()),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="valuespage",
            name="featured_blog_posts",
            field=wagtail.fields.StreamField(
                [
                    (
                        "blog_post",
                        wagtail.blocks.PageChooserBlock(page_type=["blog.BlogPage"]),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name="Blog posts",
            ),
        ),
        migrations.AlterField(
            model_name="valuespage",
            name="standout_items",
            field=wagtail.fields.StreamField(
                [
                    (
                        "item",
                        wagtail.blocks.StructBlock(
                            [
                                ("subtitle", wagtail.blocks.CharBlock()),
                                ("title", wagtail.blocks.CharBlock()),
                                ("description", wagtail.blocks.TextBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "link",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "internal",
                                                wagtail.blocks.PageChooserBlock(),
                                            ),
                                            ("external", wagtail.blocks.URLBlock()),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
