# Generated by Django 2.2.17 on 2022-01-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0030_update_image_model"),
        ("people", "0031_merge_20211105_1626"),
    ]

    operations = []
