# Generated by Django 3.2.12 on 2022-04-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0031_auto_20220422_1515"),
        ("people", "0032_merge_20220121_0913"),
    ]

    operations = []
