# Generated by Django 3.2.16 on 2023-03-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_alter_contact_phone_number'),
        ('people', '0033_merge_20220427_1056'),
    ]

    operations = [
    ]
