# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-21 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0008_remove_workpage_body"),
    ]

    operations = [
        migrations.RemoveField(model_name="workindexpage", name="show_in_play_menu",),
        migrations.RemoveField(model_name="workpage", name="show_in_play_menu",),
    ]
