# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0010_rename_streamfield_to_body"),
    ]

    operations = [
        migrations.RemoveField(model_name="workpage", name="marketing_only",),
    ]
