# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0014_map_tags_to_related_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpage",
            name="body_word_count",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
