# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-22 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0016_rename_summary_to_listing_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workpage",
            name="listing_summary",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
