# Generated by Django 2.1.5 on 2019-02-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0017_listing_summary_not_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpage", name="client", field=models.TextField(blank=True),
        ),
    ]
