# Generated by Django 2.1.5 on 2019-03-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0018_workpage_client"),
    ]

    operations = [
        migrations.RemoveField(model_name="workpage", name="descriptive_title",),
    ]
