# Generated by Django 3.2.18 on 2023-06-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_add_mailchimp_block'),
        ('work', '0028_add_video_block'),
    ]

    operations = [
    ]
