# Generated by Django 3.2.20 on 2023-10-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0030_add_social_fields_to_all_page_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workpage",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Post date"),
        ),
    ]
