FROM python:3.8-buster as backend

RUN useradd -m tbx

# Install AWS CLI
RUN curl -sSL https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o /tmp/awscli-bundle.zip && \
    unzip -q /tmp/awscli-bundle.zip -d /tmp && \
    /tmp/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws && \
    rm -rf /tmp/awscli-bundle.zip /tmp/awscli-bundle

# Install Heroku CLI
RUN curl -sSL https://cli-assets.heroku.com/install-ubuntu.sh | sh

USER tbx
