# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 10:29


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0016_auto_20160205_1724"),
        ("torchbox", "0015_auto_20160218_1201"),
    ]

    operations = []
