# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 10:29

# Manually modified during merge commit 2016-03-09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0016_reasontojoin_subtitle'),
        ('torchbox', '0016_auto_20160205_1724'),
    ]

    operations = [
    ]
