# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0017_merge'),
        ('torchbox', '0015_auto_20160218_1201'),
    ]

    operations = [
    ]
