# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0018_merge'),
        ('torchbox', '0018_auto_20160222_1029'),
    ]

    operations = [
    ]
