# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 10:35


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0016_reasontojoin_subtitle"),
        ("torchbox", "0020_auto_20160317_0955"),
    ]

    operations = []
