# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 14:08


from django.db import migrations, models
import tbx.core.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0020_auto_20160317_0955"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpagerelatedlink",
            name="link_external",
            field=models.URLField(blank=True, verbose_name="External link"),
        ),
        migrations.AlterField(
            model_name="blogindexpagerelatedlink",
            name="title",
            field=models.CharField(help_text="Link title", max_length=255),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="author_left",
            field=models.CharField(
                blank=True, help_text="author who has left Torchbox", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateField(verbose_name="Post date"),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="streamfield",
            field=wagtail.fields.StreamField(
                (
                    ("h2", wagtail.blocks.CharBlock(classname="title", icon="title"),),
                    ("h3", wagtail.blocks.CharBlock(classname="title", icon="title"),),
                    ("h4", wagtail.blocks.CharBlock(classname="title", icon="title"),),
                    ("intro", wagtail.blocks.RichTextBlock(icon="pilcrow")),
                    ("paragraph", wagtail.blocks.RichTextBlock(icon="pilcrow")),
                    (
                        "aligned_image",
                        wagtail.blocks.StructBlock(
                            (
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("alignment", tbx.core.blocks.ImageFormatChoiceBlock()),
                                ("caption", wagtail.blocks.CharBlock()),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ),
                            label="Aligned image",
                        ),
                    ),
                    (
                        "bustout",
                        wagtail.blocks.StructBlock(
                            (
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("text", wagtail.blocks.RichTextBlock()),
                            )
                        ),
                    ),
                    (
                        "pullquote",
                        wagtail.blocks.StructBlock(
                            (
                                (
                                    "quote",
                                    wagtail.blocks.CharBlock(classname="quote title"),
                                ),
                                ("attribution", wagtail.blocks.CharBlock()),
                            )
                        ),
                    ),
                    (
                        "raw_html",
                        wagtail.blocks.RawHTMLBlock(icon="code", label="Raw HTML"),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock(icon="code")),
                )
            ),
        ),
        migrations.AlterField(
            model_name="blogpagerelatedlink",
            name="link_external",
            field=models.URLField(blank=True, verbose_name="External link"),
        ),
        migrations.AlterField(
            model_name="blogpagerelatedlink",
            name="title",
            field=models.CharField(help_text="Link title", max_length=255),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_video_id",
            field=models.IntegerField(
                blank=True,
                help_text="Optional. The numeric ID of a Vimeo video to replace the background image.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="personpagerelatedlink",
            name="link_external",
            field=models.URLField(blank=True, verbose_name="External link"),
        ),
        migrations.AlterField(
            model_name="personpagerelatedlink",
            name="title",
            field=models.CharField(help_text="Link title", max_length=255),
        ),
        migrations.AlterField(
            model_name="servicespagerelatedlink",
            name="link_external",
            field=models.URLField(blank=True, verbose_name="External link"),
        ),
        migrations.AlterField(
            model_name="servicespagerelatedlink",
            name="title",
            field=models.CharField(help_text="Link title", max_length=255),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="streamfield",
            field=wagtail.fields.StreamField(
                (
                    ("h2", wagtail.blocks.CharBlock(classname="title", icon="title"),),
                    ("h3", wagtail.blocks.CharBlock(classname="title", icon="title"),),
                    ("h4", wagtail.blocks.CharBlock(classname="title", icon="title"),),
                    ("intro", wagtail.blocks.RichTextBlock(icon="pilcrow")),
                    ("paragraph", wagtail.blocks.RichTextBlock(icon="pilcrow")),
                    (
                        "aligned_image",
                        wagtail.blocks.StructBlock(
                            (
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("alignment", tbx.core.blocks.ImageFormatChoiceBlock()),
                                ("caption", wagtail.blocks.CharBlock()),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ),
                            label="Aligned image",
                        ),
                    ),
                    (
                        "bustout",
                        wagtail.blocks.StructBlock(
                            (
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("text", wagtail.blocks.RichTextBlock()),
                            )
                        ),
                    ),
                    (
                        "pullquote",
                        wagtail.blocks.StructBlock(
                            (
                                (
                                    "quote",
                                    wagtail.blocks.CharBlock(classname="quote title"),
                                ),
                                ("attribution", wagtail.blocks.CharBlock()),
                            )
                        ),
                    ),
                    (
                        "raw_html",
                        wagtail.blocks.RawHTMLBlock(icon="code", label="Raw HTML"),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock(icon="code")),
                )
            ),
        ),
        migrations.AlterField(
            model_name="standardpageclients",
            name="link_external",
            field=models.URLField(blank=True, verbose_name="External link"),
        ),
        migrations.AlterField(
            model_name="standardpageclients",
            name="title",
            field=models.CharField(help_text="Link title", max_length=255),
        ),
        migrations.AlterField(
            model_name="standardpagerelatedlink",
            name="link_external",
            field=models.URLField(blank=True, verbose_name="External link"),
        ),
        migrations.AlterField(
            model_name="standardpagerelatedlink",
            name="title",
            field=models.CharField(help_text="Link title", max_length=255),
        ),
        migrations.AlterField(
            model_name="workpage",
            name="streamfield",
            field=wagtail.fields.StreamField(
                (
                    ("h2", wagtail.blocks.CharBlock(classname="title", icon="title"),),
                    ("h3", wagtail.blocks.CharBlock(classname="title", icon="title"),),
                    ("h4", wagtail.blocks.CharBlock(classname="title", icon="title"),),
                    ("intro", wagtail.blocks.RichTextBlock(icon="pilcrow")),
                    ("paragraph", wagtail.blocks.RichTextBlock(icon="pilcrow")),
                    (
                        "aligned_image",
                        wagtail.blocks.StructBlock(
                            (
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("alignment", tbx.core.blocks.ImageFormatChoiceBlock()),
                                ("caption", wagtail.blocks.CharBlock()),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ),
                            label="Aligned image",
                        ),
                    ),
                    (
                        "bustout",
                        wagtail.blocks.StructBlock(
                            (
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("text", wagtail.blocks.RichTextBlock()),
                            )
                        ),
                    ),
                    (
                        "pullquote",
                        wagtail.blocks.StructBlock(
                            (
                                (
                                    "quote",
                                    wagtail.blocks.CharBlock(classname="quote title"),
                                ),
                                ("attribution", wagtail.blocks.CharBlock()),
                            )
                        ),
                    ),
                    (
                        "raw_html",
                        wagtail.blocks.RawHTMLBlock(icon="code", label="Raw HTML"),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock(icon="code")),
                )
            ),
        ),
    ]
