# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0021_merge'),
        ('torchbox', '0019_merge'),
    ]

    operations = [
    ]
