# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 11:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0021_merge"),
        (
            "torchbox",
            "0022_signupformpage_signupformpagebullet_signupformpagelogo_signupformpagequote_signupformpageresponse",
        ),
    ]

    operations = []
