# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 16:45


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0023_merge"),
    ]

    operations = [
        migrations.RemoveField(model_name="reasontojoin", name="subtitle",),
    ]
