# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0025_marketinglandingpagepageclients'),
        ('torchbox', '0023_merge'),
    ]

    operations = [
    ]
