# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 10:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0024_remove_reasontojoin_subtitle"),
        ("torchbox", "0025_marketinglandingpagepageclients"),
    ]

    operations = []
