# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0026_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='planet_drupal',
            field=models.BooleanField(default=False, help_text='Tick to include this post on Planet Drupal. Posts must conform to the guidelines at https://www.drupal.org/planet/guidelines'),
        ),
    ]
