# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-03 16:18


from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0026_merge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                verbose_name="Intro (used for blog index and Planet Drupal listings)",
            ),
        ),
    ]
