# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 10:46


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0029_homepagehero"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepagehero", old_name="image", new_name="background",
        ),
        migrations.AddField(
            model_name="homepagehero",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="torchbox.TorchboxImage",
            ),
        ),
    ]
