# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 09:20


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0027_auto_20160603_1718"),
        ("torchbox", "0029_auto_20160601_1630"),
    ]

    operations = []
