# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 08:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0030_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="canonical_url",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
