# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 13:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0031_blogpage_homepage_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobindexpagejob",
            name="job_intro",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
