# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 14:40


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0032_jobindexpagejob_job_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagehero",
            name="colour",
            field=models.CharField(
                default="",
                help_text="Colour of link and background gradient, defaults to blue",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
