# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 15:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0033_homepagehero_colour"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpage",
            name="descriptive_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepagehero",
            name="colour",
            field=models.CharField(
                blank=True,
                help_text="Hex ref colour of link and background gradient, defaults to blue, for example #ffffff",
                max_length=255,
            ),
        ),
    ]
