# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 13:41


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0037_auto_20160701_1307"),
        ("torchbox", "0030_merge"),
    ]

    operations = []
