# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 11:23


from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0040_auto_20160707_1218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactformfield",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_fields",
                to="torchbox.Contact",
            ),
        ),
    ]
