# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 13:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0047_homepagehero_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="personpage",
            name="is_senior",
            field=models.BooleanField(default=False),
        ),
    ]
