# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 13:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0048_personpage_is_senior"),
    ]

    operations = [
        migrations.RemoveField(model_name="personindexpage", name="intro",),
        migrations.RemoveField(model_name="personindexpage", name="show_in_play_menu",),
    ]
