# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0031_blogpage_canonical_url'),
        ('torchbox', '0049_auto_20160819_1421'),
    ]

    operations = [
    ]
