# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 11:13


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0031_blogpage_canonical_url"),
        ("torchbox", "0051_mainmenu_mainmenuitem"),
        ("torchbox", "0050_auto_20160826_1123"),
    ]

    operations = []
