# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 11:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0052_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobindexpage",
            name="reasons_intro",
            field=models.TextField(blank=True),
        ),
    ]
