# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 15:57


from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0053_jobindexpage_reasons_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobindexpage",
            name="listing_intro",
            field=models.TextField(
                blank=True,
                help_text="Shown instead of the intro when job listings are included on other pages",
            ),
        ),
        migrations.AlterField(
            model_name="jobindexpage", name="intro", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jobindexpage",
            name="no_jobs_that_fit",
            field=wagtail.fields.RichTextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
