# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 10:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0056_workpage_visit_the_site"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpage", name="homepage_color",),
        migrations.AddField(
            model_name="blogpage",
            name="colour",
            field=models.TextField(
                blank=True,
                verbose_name="Listing card colour (orange, blue, white) if left blank will display image",
            ),
        ),
    ]
