# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-02 15:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0060_auto_20160901_1658"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workpage",
            name="visit_the_site",
            field=models.URLField(blank=True),
        ),
    ]
