# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 08:49


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0062_auto_20160905_1151"),
    ]

    operations = [
        migrations.RemoveField(model_name="aboutpagevalue", name="image",),
        migrations.RemoveField(model_name="aboutpagevalue", name="page",),
        migrations.RemoveField(model_name="aboutpage", name="values_title",),
        migrations.DeleteModel(name="AboutPageValue",),
    ]
