# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 15:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0066_auto_20160906_1624"),
    ]

    operations = [
        migrations.AddField(
            model_name="personindexpage",
            name="intro",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personindexpage",
            name="senior_management_intro",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personindexpage",
            name="team_intro",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
