# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 09:15


from django.db import migrations, models
import django.db.models.deletion
import wagtail.models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0028_merge"),
        ("torchbox", "0067_auto_20160906_1651"),
    ]

    operations = [
        migrations.AddField(
            model_name="torchboximage",
            name="collection",
            field=models.ForeignKey(
                default=wagtail.models.get_root_collection_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.Collection",
                verbose_name="collection",
            ),
        ),
    ]
