# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailimages.models


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0068_torchboximage_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torchboxrendition',
            name='file',
            field=models.ImageField(height_field='height', upload_to=wagtail.wagtailimages.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
