# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 15:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0070_auto_20160915_1031"),
    ]

    operations = [
        migrations.RenameField(
            model_name="globalsettings",
            old_name="BristolAddress",
            new_name="bristol_address",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="BristolAddressLink",
            new_name="bristol_address_link",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="BristolAddressSVG",
            new_name="bristol_address_svg",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="BristolAddressTitle",
            new_name="bristol_address_title",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="ContactEmail",
            new_name="contact_email",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="ContactTelephone",
            new_name="contact_telephone",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="ContactTwitter",
            new_name="contact_twitter",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="EmailNewsletterTeaser",
            new_name="email_newsletter_teaser",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="OxfordAddress",
            new_name="oxford_address",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="OxfordAddressLink",
            new_name="oxford_address_link",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="OxfordAddressSVG",
            new_name="oxford_address_svg",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="OxfordAddressTitle",
            new_name="oxford_address_title",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="PhiliAddress",
            new_name="phili_address",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="PhiliAddressLink",
            new_name="phili_address_link",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="PhiliAddressSVG",
            new_name="phili_address_svg",
        ),
        migrations.RenameField(
            model_name="globalsettings",
            old_name="PhiliAddressTitle",
            new_name="phili_address_title",
        ),
    ]
