# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-15 10:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0068_auto_20160909_1100"),
        ("torchbox", "0070_auto_20160915_1031"),
    ]

    operations = []
