# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 10:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0071_auto_rename_global_settings_fields"),
        ("torchbox", "0071_merge"),
    ]

    operations = []
