# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 11:38


from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0029_unicode_slugfield_dj19"),
        ("torchbox", "0073_auto_20161026_1023"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "streamfield",
                    wagtail.fields.StreamField(
                        [
                            (
                                b"case_studies",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            b"title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            b"intro",
                                            wagtail.blocks.TextBlock(required=True),
                                        ),
                                        (
                                            b"case_studies",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.PageChooserBlock(
                                                    ["torchbox.WorkPage"]
                                                )
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                b"highlights",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            b"intro",
                                            wagtail.blocks.TextBlock(required=True),
                                        ),
                                        (
                                            b"highlights",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.TextBlock()
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                b"pull_quote",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            b"quote",
                                            wagtail.blocks.CharBlock(
                                                classname="quote title"
                                            ),
                                        ),
                                        (b"attribution", wagtail.blocks.CharBlock(),),
                                    ],
                                    template="blocks/pull_quote_block.html",
                                ),
                            ),
                            (
                                b"process",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            b"title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            b"steps",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                        (
                                                            "icon",
                                                            wagtail.blocks.CharBlock(
                                                                help_text="Paste SVG code here",
                                                                max_length=9000,
                                                                required=True,
                                                            ),
                                                        ),
                                                        (
                                                            "description",
                                                            wagtail.blocks.TextBlock(
                                                                required=True
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                b"people",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            b"title",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            b"intro",
                                            wagtail.blocks.TextBlock(required=True),
                                        ),
                                        (
                                            b"people",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.PageChooserBlock()
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ]
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="personpage",
            name="short_biography",
            field=models.CharField(
                blank=True,
                help_text="A shorter summary biography for including in other pages",
                max_length=255,
            ),
        ),
    ]
