# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0071_merge'),
        ('torchbox', '0074_servicepage'),
    ]

    operations = [
    ]
