# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 09:29


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0072_merge"),
        ("torchbox", "0075_auto_20161124_0845"),
    ]

    operations = []
