# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-24 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0076_merge'),
        ('torchbox', '0075_merge'),
    ]

    operations = [
    ]
