# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-29 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0077_merge'),
        ('torchbox', '0078_auto_20161129_1014'),
    ]

    operations = [
    ]
