# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-29 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0080_auto_20161129_1640'),
        ('torchbox', '0079_merge'),
    ]

    operations = [
    ]
