# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-06 10:21


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0080_auto_20161129_1640"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicespageservice",
            name="link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="torchbox.ServicePage",
            ),
        ),
    ]
