# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-06 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0081_merge'),
        ('torchbox', '0081_servicespageservice_link'),
    ]

    operations = [
    ]
