# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-12 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0082_merge'),
        ('torchbox', '0082_auto_20170112_1611'),
    ]

    operations = [
    ]
