# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 13:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0082_auto_20170112_1611"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="hero_intro",),
        migrations.RemoveField(model_name="homepage", name="hero_video_id",),
        migrations.RemoveField(model_name="homepage", name="hero_video_poster_image",),
        migrations.RemoveField(model_name="homepage", name="intro_title",),
    ]
