# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 13:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0083_homepage_remove_unused_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_intro_primary",
            field=models.TextField(blank=True, default="We do digital"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_intro_secondary",
            field=models.TextField(blank=True, default="for the good guys."),
            preserve_default=False,
        ),
    ]
