# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0083_homepage_remove_unused_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_intro_primary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_intro_secondary',
            field=models.TextField(blank=True),
        ),
    ]
