# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0084_homepage_add_editable_strapline'),
        ('torchbox', '0083_merge'),
    ]

    operations = [
    ]
