# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 16:33


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0084_homepage_add_editable_strapline"),
    ]

    operations = [
        migrations.AddField(
            model_name="torchboxrendition",
            name="filter_spec",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
