# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 16:36


from django.db import migrations
from wagtail.images.utils import get_fill_filter_spec_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0085_add_filter_spec_field'),
    ]

    forward, reverse = get_fill_filter_spec_migrations('torchbox', 'TorchboxRendition')
    operations = [
        migrations.RunPython(forward, reverse),
    ]
