# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 16:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0085_add_filter_spec_field"),
    ]

    operations = [
        # Removed to make initial migrations work again
    ]
