# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-17 16:36
from __future__ import unicode_literals

from django.db import migrations
from wagtail.wagtailimages.utils import get_fill_filter_spec_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0085_upgrade_to_wagtail17'),
    ]

    forward, reverse = get_fill_filter_spec_migrations('myapp', 'CustomRendition')
    operations = [
        migrations.RunPython(forward, reverse),
    ]
