# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0089_add_subtitle_into_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='particles_css_background_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='particles_move_direction',
            field=models.PositiveSmallIntegerField(choices=[(1, 'none'), (2, 'top'), (3, 'top-right'), (4, 'right'), (5, 'bottom-right'), (6, 'bottom'), (7, 'bottom-left'), (8, 'left')], default=1),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='particles_number',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='particles_polygon_sides',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='particles_shape_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'circle'), (2, 'edge'), (3, 'triangle'), (4, 'polygon'), (5, 'star'), (6, 'image')], default=1),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='particles_size',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='particles_size_random',
            field=models.BooleanField(default=False),
        ),
    ]
