# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0089_add_subtitle_into_step'),
        ('torchbox', '0085_merge'),
    ]

    operations = [
    ]
