# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-24 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0090_servicepage_add_sign_up_form_page'),
        ('torchbox', '0090_merge'),
    ]

    operations = [
    ]
