# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-26 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0091_merge'),
        ('torchbox', '0090_auto_20170126_1319'),
    ]

    operations = [
    ]
