# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-31 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0092_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='particles_css_background_url',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='particles_move_direction',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='particles_number',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='particles_polygon_sides',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='particles_shape_type',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='particles_size',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='particles_size_random',
        ),
    ]
