# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-20 08:43


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0092_servicepage_add_logos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torchboxrendition",
            name="focal_point_key",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=16
            ),
        ),
    ]
