# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-20 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0093_wagtail19_upgrade'),
        ('torchbox', '0093_auto_20170315_1306'),
        ('torchbox', '0090_auto_20170130_1032'),
        ('torchbox', '0093_auto_20170131_1151'),
    ]

    operations = [
    ]
