# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-08 11:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0093_wagtail19_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactformfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("singleline", "Single line text"),
                    ("multiline", "Multi-line text"),
                    ("email", "Email"),
                    ("number", "Number"),
                    ("url", "URL"),
                    ("checkbox", "Checkbox"),
                    ("checkboxes", "Checkboxes"),
                    ("dropdown", "Drop down"),
                    ("multiselect", "Multiple select"),
                    ("radio", "Radio buttons"),
                    ("date", "Date"),
                    ("datetime", "Date/time"),
                ],
                max_length=16,
                verbose_name="field type",
            ),
        ),
    ]
