# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-31 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0090_auto_20170130_1032'),
        ('torchbox', '0093_auto_20170131_1151'),
    ]

    operations = [
    ]
