# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-20 11:01


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0093_auto_20170315_1306"),
        ("torchbox", "0093_wagtail19_upgrade"),
    ]

    operations = []
