# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-01 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0094_merge'),
        ('torchbox', '0091_auto_20170201_1043'),
    ]

    operations = [
    ]
