# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 14:55


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0094_auto_20170908_1245"),
        ("torchbox", "0096_revert_pr97"),
    ]

    operations = []
