# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-26 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('torchbox', '0096_revert_pr97'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='phili_address',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='phili_address_link',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='phili_address_svg',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='phili_address_title',
        ),
        migrations.AddField(
            model_name='torchboxrendition',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Filter'),
        ),
        migrations.AlterField(
            model_name='torchboxrendition',
            name='focal_point_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
