# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-30 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0100_auto_20180830_1056"),
    ]

    operations = []
