# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-12 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0100_auto_20180830_1056'),
        ('torchbox', '0100_auto_20180829_1541'),
    ]

    operations = [
    ]
