# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-18 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0102_auto_20180830_1109"),
        ("torchbox", "0101_auto_20180912_1622"),
    ]

    operations = []
