# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-28 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0103_merge_20180918_1304"),
        ("torchbox", "0102_workpage_feed_image"),
    ]

    operations = []
