# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-15 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0104_merge_20180928_1009"),
    ]

    operations = [
        migrations.AddField(
            model_name="torchboximage",
            name="file_hash",
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
    ]
