# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0105_torchboximage_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='name',
            field=models.CharField(default='Torchbox', help_text='Name', max_length=255),
        ),
    ]
