# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0106_globalsettings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='name',
            field=models.CharField(default='Main Menu', help_text='Name', max_length=255),
        ),
    ]
