# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0109_move_blog_into_new_app"),
    ]

    operations = [
        migrations.RenameModel(old_name="BlogPageTagList", new_name="Tag",),
    ]
