# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-21 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailforms", "0003_capitalizeverbose"),
        ("wagtailcore", "0040_page_draft_title"),
        ("torchbox", "0114_remove_standardpage_show_in_play_menu"),
    ]

    operations = [
        migrations.RemoveField(model_name="tshirtpage", name="main_image",),
        migrations.RemoveField(model_name="tshirtpage", name="page_ptr",),
        migrations.DeleteModel(name="TshirtPage",),
    ]
