# Generated by Django 2.1.5 on 2019-02-16 16:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0122_remove_unused_jobindexpage_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainmenu",
            name="menu",
            field=wagtail.fields.StreamField(
                [
                    (
                        "items",
                        wagtail.blocks.StructBlock(
                            [
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "subitems",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "subitem",
                                                wagtail.blocks.PageChooserBlock(),
                                            ),
                                            (
                                                "related_listing_page",
                                                wagtail.blocks.PageChooserBlock(),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
