# Generated by Django 2.1.5 on 2019-02-16 16:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0122_remove_unused_jobindexpage_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='menu',
            field=wagtail.core.fields.StreamField([('items', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('subitems', wagtail.core.blocks.StreamBlock([('subitem', wagtail.core.blocks.PageChooserBlock()), ('related_listing_page', wagtail.core.blocks.PageChooserBlock())]))]))], blank=True),
        ),
    ]
