# Generated by Django 2.1.5 on 2019-02-16 17:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0124_auto_20190216_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='menu',
            field=wagtail.core.fields.StreamField([('items', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock()), ('subitems', wagtail.core.blocks.StreamBlock([('related_listing_page', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True))]))], blank=True),
        ),
    ]
