# Generated by Django 2.2.3 on 2019-09-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_contactreasonslist_is_default_not_unique'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('services', '0029_subservice_listingsettings'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('torchbox', '0125_auto_20190216_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontentblock',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutpagecontentblock',
            name='page',
        ),
        migrations.RemoveField(
            model_name='aboutpageoffice',
            name='page',
        ),
        migrations.RemoveField(
            model_name='aboutpagerelatedlinkbutton',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='aboutpagerelatedlinkbutton',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='aboutpagerelatedlinkbutton',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepageclient',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepageclient',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepageclient',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepageclient',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagehero',
            name='background',
        ),
        migrations.RemoveField(
            model_name='homepagehero',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='homepagehero',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='homepagehero',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='homepagehero',
            name='page',
        ),
        migrations.DeleteModel(
            name='ParticleSnippet',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='AboutPageContentBlock',
        ),
        migrations.DeleteModel(
            name='AboutPageOffice',
        ),
        migrations.DeleteModel(
            name='AboutPageRelatedLinkButton',
        ),
        migrations.DeleteModel(
            name='HomePageClient',
        ),
        migrations.DeleteModel(
            name='HomePageHero',
        ),
    ]
