# Generated by Django 2.2.12 on 2020-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0125_auto_20190216_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobindexpage",
            name="jobs_xml_feed",
            field=models.URLField(blank=True),
        ),
    ]
