# Generated by Django 2.2.3 on 2020-01-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0126_auto_20190912_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='torchboximage',
            name='traced_SVG_hash',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='torchboximage',
            name='traced_SVG_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
