# Generated by Django 2.2.12 on 2020-05-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0128_notfoundpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='blog_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='clients_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_intro_primary',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_intro_secondary',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='work_title',
        ),
    ]
