# Generated by Django 2.2.17 on 2021-05-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0024_auto_20210412_1428"),
        ("torchbox", "0135_eventindexpage_eventindexpageevents"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventindexpageevents",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="people.Author",
            ),
        ),
        migrations.AlterField(
            model_name="eventindexpageevents",
            name="date",
            field=models.DateField(verbose_name="Event date"),
        ),
        migrations.AlterField(
            model_name="eventindexpageevents",
            name="link_external",
            field=models.URLField(verbose_name="External link"),
        ),
        migrations.AlterField(
            model_name="eventindexpageevents", name="title", field=models.TextField(),
        ),
    ]
