# Generated by Django 2.2.17 on 2021-08-02 14:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0137_auto_20210802_1445"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalsettings",
            name="addresses",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "address",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("title", wagtail.core.blocks.CharBlock(blank=True)),
                                (
                                    "address",
                                    wagtail.core.blocks.RichTextBlock(blank=True),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
