# Generated by Django 2.2.17 on 2021-11-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0140_update_image_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="torchboxrendition", unique_together=None,),
        migrations.RemoveField(model_name="torchboxrendition", name="image",),
        migrations.DeleteModel(name="TorchboxImage",),
        migrations.DeleteModel(name="TorchboxRendition",),
    ]
