# Generated by Django 3.2.18 on 2023-06-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0146_alter_standardpage_additional_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='site',
        ),
    ]
