# Generated by Django 3.2.18 on 2023-06-26 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("torchbox", "0147_call_to_action"),
        ("torchbox", "0147_cleanup_old_database_schema_and_tables"),
    ]

    operations = []
