# Generated by Django 3.2.18 on 2023-06-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0147_add_mailchimp_block'),
        ('torchbox', '0149_add_video_block'),
    ]

    operations = [
    ]
