# Generated by Django 3.2.18 on 2023-07-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0150_add_mailchimp_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='site',
        ),
    ]
