# Generated by Django 4.2.8 on 2024-03-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torchbox", "0153_change_minimum_number_for_key_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediasettings",
            name="site_name",
            field=models.CharField(
                blank=True,
                default="Torchbox",
                help_text="Site name, used by Open Graph.",
                max_length=255,
            ),
        ),
    ]
