# Generated by Django 3.2.18 on 2023-06-26 10:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechBlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tech Blog Tag',
            },
        ),
        migrations.CreateModel(
            name='TaggedTechBlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='tech_blog.techblogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_blog_posts', to='tech_blog.techblogtag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='techblogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tech_blog.TaggedTechBlogPost', to='tech_blog.TechBlogTag', verbose_name='Tags'),
        ),
    ]
