# Generated by Django 3.2.18 on 2023-06-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0002_auto_20230626_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='techblogpage',
            name='body_word_count',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
