# Generated by Django 3.2.18 on 2023-06-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_blog', '0004_alter_techblogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='techblogpage',
            name='listing_summary',
            field=models.TextField(blank=True),
        ),
    ]
