# Generated by Django 2.1.5 on 2019-02-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_initial_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
