# Generated by Django 3.2.13 on 2022-10-04 11:16

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionpage',
            name='clients_section_body',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading2_block.html')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading3_block.html')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading4_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow', template='patterns/molecules/streamfield/blocks/paragraph_block.html')), ('embed_plus_cta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('intro', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.PageChooserBlock()), ('button_text', wagtail.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Youtube Embed'))], icon='code', label='Embed + CTA', template='patterns/molecules/streamfield/blocks/embed_plus_cta_block.html'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='propositionpage',
            name='services_section_body',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading2_block.html')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading3_block.html')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading4_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow', template='patterns/molecules/streamfield/blocks/paragraph_block.html')), ('embed_plus_cta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('intro', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.PageChooserBlock()), ('button_text', wagtail.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Youtube Embed'))], icon='code', label='Embed + CTA', template='patterns/molecules/streamfield/blocks/embed_plus_cta_block.html'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='propositionpage',
            name='team_section_body',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading2_block.html')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading3_block.html')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading4_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow', template='patterns/molecules/streamfield/blocks/paragraph_block.html')), ('embed_plus_cta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('intro', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.PageChooserBlock()), ('button_text', wagtail.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Youtube Embed'))], icon='code', label='Embed + CTA', template='patterns/molecules/streamfield/blocks/embed_plus_cta_block.html'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='propositionsubpage',
            name='clients_section_body',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading2_block.html')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading3_block.html')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading4_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow', template='patterns/molecules/streamfield/blocks/paragraph_block.html')), ('embed_plus_cta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('intro', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.PageChooserBlock()), ('button_text', wagtail.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Youtube Embed'))], icon='code', label='Embed + CTA', template='patterns/molecules/streamfield/blocks/embed_plus_cta_block.html'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='propositionsubpage',
            name='services_section_body',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading2_block.html')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading3_block.html')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading4_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow', template='patterns/molecules/streamfield/blocks/paragraph_block.html')), ('embed_plus_cta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('intro', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.PageChooserBlock()), ('button_text', wagtail.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Youtube Embed'))], icon='code', label='Embed + CTA', template='patterns/molecules/streamfield/blocks/embed_plus_cta_block.html'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='propositionsubpage',
            name='team_section_body',
            field=wagtail.fields.StreamField([('h2', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading2_block.html')), ('h3', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading3_block.html')), ('h4', wagtail.blocks.CharBlock(form_classname='title', icon='title', template='patterns/molecules/streamfield/blocks/heading4_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow', template='patterns/molecules/streamfield/blocks/paragraph_block.html')), ('embed_plus_cta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('intro', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.PageChooserBlock()), ('button_text', wagtail.blocks.CharBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Youtube Embed'))], icon='code', label='Embed + CTA', template='patterns/molecules/streamfield/blocks/embed_plus_cta_block.html'))], blank=True, use_json_field=True),
        ),
    ]
