# Generated by Django 3.2.16 on 2023-04-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0008_auto_20230317_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionpage',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('coral', 'Coral'), ('dark', 'Dark')], default='light', max_length=255),
        ),
    ]
