# Generated by Django 3.2.18 on 2023-06-20 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("propositions", "0009_auto_20230503_1527"),
        ("propositions", "0009_alter_propositionpage_theme"),
    ]

    operations = []
