# Generated by Django 3.2.18 on 2023-06-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0010_data_migration_proposition_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionpage',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('coral', 'Coral'), ('dark', 'Dark')], default='light', max_length=255),
        ),
    ]
