# Generated by Django 3.2.18 on 2023-08-08 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("propositions", "0011_add_social_fields_to_all_page_types"),
        ("propositions", "0011_subpropositionpage"),
    ]

    operations = []
