# Generated by Django 3.2.20 on 2023-11-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propositions", "0015_add_optional_link_to_testimonials"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubServicePageToSubPropositionPageMigration",
        ),
    ]
