# Generated by Django 3.2.20 on 2023-11-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0016_add_work_and_thinking_to_proposition_page'),
        ('propositions', '0017_remove_heading_for_processes_field'),
    ]

    operations = [
    ]
