# Generated by Django 3.2.18 on 2023-06-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_alter_navigationsettings_footer_logos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='site',
        ),
    ]
