# Generated by Django 3.2.18 on 2023-06-15 13:25

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0008_alter_navigationsettings_footer_logos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigationsettings",
            name="footer_top_links",
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "external_link",
                                    wagtail.blocks.URLBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Single list of elements at the base of the page.",
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="primary_navigation",
            field=wagtail.fields.StreamField(
                [
                    (
                        "link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "external_link",
                                    wagtail.blocks.URLBlock(required=False),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Leave blank to use the page's own title",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Main site navigation",
                use_json_field=True,
            ),
        ),
    ]
