# Generated by Django 3.2.18 on 2023-06-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "navigation",
            "0009_add_externallink_to_linkblock_and_remove_footer_top_links_from_navigationsettings",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigationsettings",
            name="footer_teasers",
        ),
    ]
