# Generated by Django 3.2.18 on 2023-07-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0010_remove_navigationsettings_footer_teasers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='site',
        ),
    ]
