# Generated by Django 3.2.16 on 2022-12-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0031_auto_20220422_1515"),
        ("impact_reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ImpactBlockPageAuthor",
            new_name="ImpactReportPageAuthor",
        ),
    ]
