# Generated by Django 3.2.16 on 2022-12-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_alter_customimage_file_hash"),
        ("impact_reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactreportpage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
