# Generated by Django 2.2.24 on 2021-06-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="event", options={},),
    ]
